apiVersion: batch/v1
kind: Job
metadata:
  name: job-secret
spec:
  template:
    spec:
      containers:
        - name: job-secret
          image: busybox
          command: ["sh", "-c", "echo 'Hello, World!' && sleep 30"]
      restartPolicy: Never