apiVersion: v1
kind: Secret
metadata:
  name: prompt2video-primarybackend-secret
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9iaWNreXlhZGF2MjAwNV9kYl91c2VyOkJpY2t5NjIzNEBjbHVzdGVyMC5zcWx1dHYyLm1vbmdvZGIubmV0Lw==
  DB_NAME: TWFuaW1fdmlkZW9fZ2VuZXJhdGlvbl9haQ==
  REDIS_URL: cmVkaXMtMTkyMjMuYzgudXMtZWFzdC0xLTMuZWMyLmNsb3VkLnJlZGlzbGFicy5jb20=
  REDIS_PORT: MTkyMjM=
  REDIS_PASSWORD: eHc2Smw2Ykp6QmI1bVRmR0xHeW1GanNIbTBoMW1ad3A=

