apiVersion: v1
kind: Service
metadata:
  name: prompt2video-primarybackend-service
spec:
  selector:
    app: prompt2video-primarybackend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
