apiVersion: apps/v1
kind: Deployment
metadata:
  name: prompt2videoworker-deployment
  labels:
    app: prompt2videoworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prompt2videoworker 
  template:
    metadata:
      labels:
        app: prompt2videoworker
    spec:
      containers:
      - name: prompt2videoworker
        image: bicky2005/prompt2videoworker:latest
        ports:
        - containerPort: 80
        envFrom:
            - secretRef:
                name: prompt2videoworker-secret
