apiVersion: v1
kind: Secret
metadata:
  name: prompt2videoworker-secret
data:
  REDIS_URL: cmVkaXMtMTkyMjMuYzgudXMtZWFzdC0xLTMuZWMyLmNsb3VkLnJlZGlzbGFicy5jb20=
  REDIS_PORT: MTkyMjM=
  REDIS_PASSWORD: eHc2Smw2Ykp6QmI1bVRmR0xHeW1GanNIbTBoMW1ad3A=
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9iaWNreXlhZGF2MjAwNV9kYl91c2VyOkJpY2t5NjIzNEBjbHVzdGVyMC5zcWx1dHYyLm1vbmdvZGIubmV0Lw==
  DB_NAME: TWFuaW1fdmlkZW9fZ2VuZXJhdGlvbl9haQ==
  PRIMARY_BACKEND_URL: aHR0cHM6Ly8xZTI0MThjNWE3NTcubmdyb2stZnJlZS5hcHA=
  GEMINI_API_KEY: QUl6YVN5Q1QyWFh0V1lRb2lqZmJNUXFLNFBYaHFoMThtZXc0eVo0
  CLOUDINARY_CLOUD_NAME: ZHlrcGZheXdo
  CLOUDINARY_API_KEY: NDI4Nzk3ODg1MTY2Nzk0
  CLOUDINARY_SECRET_KEY: MTdqQU9EblMySWNVY05ycE9qMTlhY2REZExV
  BACKEND_URL: aHR0cHM6Ly8xZTI0MThjNWE3NTcubmdyb2stZnJlZS5hcHA=